$('.placeSelectButton').click(function(){
    console.log($(this).attr('id'));
    $('#placeSelector').modal('toggle');
});
$('.deckSelectButton').click(function(){
    console.log($(this).attr('id'));
});
$('.arcanaSelectButton').click(function(){
    console.log($(this).attr('id'));
});
$('.cardSelectButton').click(function(){
    console.log($(this).attr('id'));
});
$('#putCard').click(function(){
    $('#placeSelector').modal('toggle');
});